Repository godotengine/godot-blender-exporter, pull requests merged in 2020-10, with the labels that each got.

#368 Update pylint to 2.5.3
  requirements.txt
Labels: bug

#369 Check if object has parent instead of checking if parent is None
  io_scene_godot/export_godot.py
Labels: bug

#377 Fix CI
  tests/reference_exports/action_with_constraint/constraint_with_undeform_bone.escn
Labels: bug

#370 Make the "experimental" signaling more prominent in the README
  README.md
Labels: documentation, enhancement

#362 Clarify warning message for unsupported light.
  io_scene_godot/converters/simple_nodes.py
Labels: enhancement
