Repository godotengine/godot-blender-exporter, pull requests merged in 2021-07, with the labels that each got.

#402 Fix small typo in instructions
  README.md
Labels: bug

#405 Added 2 new blender nodes and fixed some Godot shader issues
  io_scene_godot/converters/material/script_shader/node_converters.py
  io_scene_godot/converters/material/script_shader/shader_functions.py
Labels: bug, enhancement

#376 add ShaderFunction for vector element-wise multiplication
  io_scene_godot/converters/material/script_shader/shader_functions.py
Labels: enhancement
